### ISSUE TITLE
Marking old translations fix

### ISSUE THREAD

**Issue by vlad-timotei** [Mte90/GlotDict#293]
On [this page](https://translate.wordpress.org/projects/wp/4.1.x/ro/default/?filters%5Bterm%5D=&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current&filters%5Buser_login%5D=&sort%5Bby%5D=translation_date_added&sort%5Bhow%5D=asc&sorts=Apply+Sorting) all strings are older than 6 months, they should all be marked, but they are not:

![image](https://user-images.githubusercontent.com/65488419/130962201-6a9c2957-eea5-45e2-919f-29f08e275dab.png)

The issue originates in the fact that the CSS rules need to be updated.
`.has-old-string td:last-child` is selecting the custom column added by GD with buttons.
https://github.com/Mte90/GlotDict/blob/bc2cf68df6d8c97560258d2f6f17cca03f8b39fb/css/style.css#L5-L8

I propose to update that to:
```css
.has-old-string td:nth-last-child(2),.has-old-string th:nth-last-child(2),.box.has-old-string{
	border-right-width: 2px !important;
	border-right-color: black !important;
}
```

After the patch:
![image](https://user-images.githubusercontent.com/65488419/130962867-23d544b0-3297-4c63-b2a1-2bda9a2de6c8.png)

It also applies correctly for non GTE/PTE users:
![image](https://user-images.githubusercontent.com/65488419/130962937-6656ffa6-b088-4b7a-a936-2f66f401ff69.png)
